### ISSUE TITLE
Doesn't upload on OS X. 

### ISSUE THREAD

**Issue by brnrdbrk** [Facepunch/rust-sdk#2]
Rust SDK doesn't seem to upload the material and the texture ( file size is 0.0 MB on the workshop item page). 

I will check the upload script and see if I can debut this further.

**Comment by garrynewman** [comment]
Do you get any errors in the console window?

**Comment by brnrdbrk** [comment]
That was fast. Nope, no errors in the console.

**Comment by brnrdbrk** [comment]
Although I only updated the skin. I'll try to upload a new skin later today and report if I get a log in the console.

**Comment by brnrdbrk** [comment]
Well, just tried to upload a fresh skin (pants.blank) and got this log output in the console: 

RESULT:k_EResultOK
UnityEngine.Debug:Log(Object)

ID:490383785
UnityEngine.Debug:Log(Object)

It still doesn't seem to upload, file size on the workshop page still says 0.00 MB. Icon, description pushes fine.

**Comment by garrynewman** [comment]
I think I know what this is - will boot up my mac and try to get it working

**Comment by brnrdbrk** [comment]
Thanks! If you need anything else from me just shout!

**Comment by garrynewman** [comment]
Is this still an issue?

**Comment by brnrdbrk** [comment]
It was yesterday. Give me 15 mins and I'll check.

**Comment by brnrdbrk** [comment]
Yes it is. Still 0.00 MB on the website. http://steamcommunity.com/id/brnrdbrk/myworkshopfiles/?appid=252490

I uploaded a fresh skin and no errors, only the standard Debug.Log output (ResultOK, ID, Path, Preview Path)

**Comment by garrynewman** [comment]
What paths does it print? Are they correct?

**Comment by brnrdbrk** [comment]
Path is /Users/brnrdbrk/Library/Application Support/Steam/SteamApps/common/RustSDK/RustSDK/Assets/Workshop/Pantsypants

The paths are correct yes.

**Comment by garrynewman** [comment]
Are the caps correct? Could be a caps sensitivity problem - although I doubt it.

**Comment by brnrdbrk** [comment]
Yeah they seem correct but I'll double check later today.

**Comment by brnrdbrk** [comment]
This is still an issue on latest SDK. Just tested with a fresh skin and the issue persists.

**Comment by ramsey138** [comment]
I'm having the same problem on Mac OSX 10.8.5. I uploaded my first skin but the file size states 0.00 MB.
