### ISSUE TITLE
OSX new assests missing

### ISSUE THREAD

**Issue by CreepzsGotYoz** [Facepunch/rust-sdk#5]
Dear Garry,
I have been experimenting and playing around with the various releases of the asset models you have been producing for the general community to experiment with, since the new sdk download I no longer receive the sdk file I would usually open the new file in UNITY and instead only receive a ignor.config license and read.me file, is this normal and Im derping more than a Gmod server coded by a script kitty or is there something wrong with the decompression or download of the source file?

I appreciate if you could reply to this and hopefully I can continue to create
Regards Creepzs,

**Comment by garrynewman** [comment]
Yeah the download is on Steam now - under the tools section

**Comment by CreepzsGotYoz** [comment]
Its good to hear from a CEO who cares about his game, But you may want to read my comments on Lua in regards to gmod under my message i replied to above
thanks
