### ISSUE TITLE
More detailed instructions for finding Rust SDK on Steam.

### ISSUE THREAD

**Issue by yagihashib** [Facepunch/rust-sdk#8]
This might be a minor issue, especially for those already familiar with Tools in the Steam library, but(being new to Steam SDK's) I had trouble initially finding where to download the Rust SDK. After quite a bit of searching, I found the answer on the Rust Reddit. Maybe you could add some clarification in the Set Up section next to 'Download the Rust SDK on Steam'?

Such as 'Download the Rust SDK on Steam (Library > Tools > Rust SDK)'

**Comment by garrynewman** [comment]
Done (on the new wiki)

**Comment by Destrovich** [comment]
Thank you very much


________________________________
